feature: Add suggest random tiktok video (#22)
* Put verify tiktok url to utils

* Add tests for suggest videos

* Fix suggest videos test

* Add get tiktok acecss token

* Finish suggest random videos

* Add auto download chrome if not exist

* Change version

* Update user

* Update requirements

* Fix CI files

* Remove unnecessary print

* Add a bit more logging for suggest_videos

* Add http tests for test_suggest_videos

* Add code for suggest videos http

* Add tests to detect bad location

* Fuck this

* Add get hardcoded videos

* Add hardcoded videos getting

* Remove unnecessary prints

* Fix up queried URL

* Add scrape links script

* Add more hardcoded

* Add more hardcoded

diff --git a/.github/workflows/deploy-to-aws.yml b/.github/workflows/deploy-to-aws.yml
--- a/.github/workflows/deploy-to-aws.yml
+++ b/.github/workflows/deploy-to-aws.yml
@@ -71,6 +71,20 @@ jobs:
           cd $HOSTING_DIR/
           echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env
 
+      - name: Check and Install Google Chrome
+        run: |
+          if ! command -v google-chrome &> /dev/null
+          then
+            echo "Google Chrome not found. Installing..."
+            wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
+            sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
+            sudo apt update
+            sudo apt install google-chrome-stable -y
+            echo "Google Chrome has been installed."
+          else
+            echo "Google Chrome is already installed."
+          fi
+
       - name: Run unit tests
         run: |
           cd $HOSTING_DIR/
